---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xnetmc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &app xnetmc
spec:
  selector:
    matchLabels:
      app: *app
  template:
    metadata:
      labels:
        app: *app
    spec:
      containers:
        - name: *app
          image: itzg/minecraft-server
          env:
            - name: EULA
              value: "true"
            - name: DIFFICULTY
              value: "hard"
            - name: TYPE
              value: "paper"
            - name: VERSION
              value: "1.21.1"
          ports:
            - containerPort: 25565
              name: main
          readinessProbe:
            exec:
              command: &livecmd
                - "/usr/local/bin/mc-monitor"
                - "status"
                - "--host"
                - "localhost"
            initialDelaySeconds: 20
            periodSeconds: 5
            failureThreshold: 20
          livenessProbe:
            exec:
              command: *livecmd
            initialDelaySeconds: 120
            periodSeconds: 60
          volumeMounts:
            - name: mc-data
              mountPath: /data
      volumes:
        - name: mc-data
          persistentVolumeClaim:
            claimName: xnetmc
