---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app metallb
  namespace: flux-system
spec:
  targetNamespace: metallb-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/metallb-system/metallb/app
  prune: false
  sourceRef:
    kind: GitRepository
    name: netcluster
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
