---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app xnetmc
  namespace: flux-system
spec:
  targetNamespace: default
  dependsOn:
    - name: longhorn
  sourceRef:
    kind: GitRepository
    name: netcluster
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  path: ./kubernetes/apps/default/minecraft/xnetmc
  prune: true
