---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app node-feature-discovery
  namespace: flux-system
spec:
  targetNamespace: kube-system
  sourceRef:
    kind: GitRepository
    name: netcluster
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  path: ./kubernetes/apps/kube-system/node-feature-discovery/app
  prune: true
  wait: false
  retryInterval: 2m
  timeout: 5m
