---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app capacitor
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: netcluster
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  path: ./kubernetes/apps/flux-system/capacitor/app
  prune: true
  retryInterval: 2m
  targetNamespace: flux-system
  timeout: 5m
  wait: true
